# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 倒一杯茶，品味苦中带甜的人生  # ex. I m Chuan
name: 快乐小岛 # ex. DONGChuan
email: chenxuanling12@outlook.com
location: Shen Zhen # ex. Nice, France
company: Happyislet
company_url: http://www.happyislet.com
github_url: https://github.com/chenxuanling12 # ex. https://github.com/DONGChuan
github_username: chenxuanling12 # ex. DONGChuan
description: 这是一个在你一天繁忙后栖息顿足的地方。
favicon: logo.png # Image must be in assets/images
repository:  chenxuanling12/Yummy-Jekyll # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://www.happyislet.com
host: happyislet.com
## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-archives

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
#    tag: '/tag/:name/'
    category: '/category/:name/'

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /category/technology/
    label: 技术杂谈
    
  -
    href: /literature/
    label: 文学殿堂

  -
    href: /art/
    label: 艺术欣赏

  -
    href: /thought/
    label: 心灵感悟
  
  -
    href: /happymoments/
    label: 开心一刻 
  -
    href: /About/
    label: 关于

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]
